@startuml

object match {
    name
}
object exercise {
    number
}
object target {
}
object passing {
    alphas
    charlies
    deltas
    misses
    penalties
    time
}
object shooter {
    name
    surname
    sex
    date of birth
}

match "1" *-- "N" exercise
exercise "1" *-right- "N" passing
exercise "1" *-down- "N" target
shooter "1" -down- "N" passing

@enduml
