@startuml

o -> (Enter passings)

left to right direction

actor Admin as a
actor Operator as o

a -> (Enter shooters)

rectangle Match {
  a -> (Create)
  a -> (Add exercises)
  a -> (Add participants)
  a -> (Print score sheets)
  a -> (Generate PDF results)
}

@enduml
