@startuml

left to right direction

actor Administrator as a
actor "Match Director" as d
actor Helper as h

a -- (Enter Shooters)

rectangle Preparation {
    d -- (Create Match)
    d -- (Add Exercises)
    d -- (Add Participants)
    d -- (Generate Score Sheets)
}

rectangle Processing {
    d -- (Generate Results)
    (Enter Passings) - h
}

@enduml
